<template>
  <div class="app-wrapper">
    <nav class="navbar">
      <div class="container nav-content">
        <div class="brand">

          <span class="nav-title">Focus Train</span>
        </div>
        <RouterLink to="/" class="back-link">← back to home</RouterLink>
      </div>
    </nav>

    <main class="container">
      <section class="hero" style="text-align: left; max-width: 800px; padding-bottom: 40px;">
        <img src="/focustrain/focustrainicon.png" alt="Focus Train" class="app-icon" style="margin-bottom: 24px;" />
        <h1 class="hero-title" style="font-size: 2.5rem; margin-bottom: 40px;">Terms and Conditions</h1>
        
        <div class="terms-content">
          <h2>1. Introduction</h2>
          <p>
            Welcome to Focus Train ("we," "our," or "us"). By downloading or using our mobile application, 
            you agree to be bound by these Terms and Conditions. If you do not agree to these terms, 
            please do not use the application.
          </p>

          <h2>2. License</h2>
          <p>
            We grant you a revocable, non-exclusive, non-transferable, limited license to download, 
            install, and use the application strictly in accordance with these Terms.
          </p>

          <h2>3. Description of Service</h2>
          <p>
            Focus Train is a productivity and focus application designed to help users improve their 
            concentration and manage their time effectively. The application provides tools for focus 
            sessions, timers, and related features.
          </p>

          <h2>4. Usage Restrictions</h2>
          <p>
            You agree not to, and you will not permit others to:
          </p>
            <ul>
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the application.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the application.</li>
              <li>Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of us or our affiliates, partners, suppliers, or the licensors of the application.</li>
            </ul>

          <h2>5. Intellectual Property</h2>
          <p>
            The application, including without limitation all copyrights, patents, trademarks, trade secrets, 
            and other intellectual property rights are, and shall remain, the sole and exclusive property of Focus Train.
          </p>

          <h2>6. User Data</h2>
          <p>
            Focus Train is designed to be privacy-first. We do not collect personal data. Any data generated by 
            your use of the application (such as focus session history or settings) is stored locally on your device.
          </p>

          <h2>7. Updates to Application</h2>
          <p>
            We may from time to time provide enhancements or improvements to the features and functionality of the 
            application, which may include patches, bug fixes, updates, upgrades, and other modifications.
          </p>

          <h2>8. Term and Termination</h2>
          <p>
            This Agreement shall remain in effect until terminated by you or us. We may, in our sole discretion, 
            at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
          </p>
          
          <h2>9. Disclaimer of Warranty</h2>
          <p>
            The Application is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. 
            To the maximum extent permitted under applicable law, we expressly disclaim all warranties, whether express, implied, statutory, or otherwise.
          </p>

          <h2>10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, in no event shall Focus Train be liable for any 
            indirect, punitive, incidental, special, consequential, or exemplary damages, including without 
            limitation damages for loss of profits, goodwill, use, data, or other intangible losses.
          </p>
        </div>
      </section>

      <section class="hero" style="text-align: left; max-width: 800px; padding-bottom: 40px; padding-top: 0;">
        <h1 class="hero-title" style="font-size: 2.5rem; margin-bottom: 40px;">Privacy Policy</h1>
        
        <div class="terms-content">
          <h2>1. Introduction</h2>
          <p>
            This Privacy Policy describes how Focus Train ("we," "our," or "us") handles information 
            when you use our mobile application. We are committed to protecting your privacy.
          </p>

          <h2>2. Information We Collect</h2>
          <p>
            Focus Train is designed with privacy at its core. We do not collect, store, or transmit 
            any personal information. All data related to your focus sessions, preferences, and settings 
            remains on your device.
          </p>

          <h2>3. Data Storage</h2>
          <p>
            All application data is stored locally on your device. We do not use cloud storage, 
            external servers, or any third-party services to store your data. If you delete the 
            application, all associated data will be removed from your device.
          </p>

          <h2>4. Third-Party Services</h2>
          <p>
            Focus Train does not integrate with any third-party analytics, advertising, or tracking 
            services. We do not share any information with third parties.
          </p>

          <h2>5. Children's Privacy</h2>
          <p>
            Our application does not address anyone under the age of 13. We do not knowingly collect 
            personally identifiable information from children under 13.
          </p>

          <h2>6. Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by 
            posting the new Privacy Policy on this page with an updated revision date.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact us at 
            <a href="mailto:trainfocus@proton.me" style="color: var(--color-primary); text-decoration: underline;">trainfocus@proton.me</a>.
          </p>
          
          <p style="margin-top: 40px; color: var(--color-text-light); font-size: 0.9rem;">
            Last updated: February 15, 2026
          </p>
        </div>
      </section>
    </main>

    <footer class="footer">
      <div class="container footer-content">
        <p>&copy; {{ new Date().getFullYear() }} Focus Train. All rights reserved.</p>
      </div>
    </footer>
  </div>
</template>

<style src="./focustrain.css"></style>

<style scoped>
.terms-content {
  color: var(--color-text);
  line-height: 1.8;
}

.terms-content h2 {
  font-size: 1.5rem;
  margin-top: 32px;
  margin-bottom: 16px;
  font-weight: 600;
  color: var(--color-text);
}

.terms-content p {
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content ul {
  padding-left: 24px;
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content li {
  margin-bottom: 8px;
}

.nav-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
}
</style>
