<template>
  <div class="app-wrapper">
    <nav class="navbar">
      <div class="container nav-content">
        <div class="brand">

          <span class="nav-title">Focus Train</span>
        </div>
        <RouterLink to="/" class="back-link">← back to home</RouterLink>
      </div>
    </nav>

    <main class="container">
      <section class="hero" style="text-align: left; max-width: 800px; padding-bottom: 40px;">
        <img src="/focustrain/focustrainicon.png" alt="Focus Train" class="app-icon" style="margin-bottom: 24px;" />
        <h1 class="hero-title" style="font-size: 2.5rem; margin-bottom: 40px;">Terms and Conditions</h1>
        
        <div class="terms-content">
          <h2>1. Introduction</h2>
          <p>
            Welcome to Focus Train ("we," "our," or "us"). By downloading or using our mobile application, 
            you agree to be bound by these Terms and Conditions. If you do not agree to these terms, 
            please do not use the application.
          </p>

          <h2>2. License</h2>
          <p>
            We grant you a revocable, non-exclusive, non-transferable, limited license to download, 
            install, and use the application strictly in accordance with these Terms.
          </p>

          <h2>3. Description of Service</h2>
          <p>
            Focus Train is a productivity and focus application designed to help users improve their 
            concentration and manage their time effectively. The application provides tools for focus 
            sessions, timers, and related features.
          </p>

          <h2>4. Usage Restrictions</h2>
          <p>
            You agree not to, and you will not permit others to:
          </p>
            <ul>
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the application.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the application.</li>
              <li>Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of us or our affiliates, partners, suppliers, or the licensors of the application.</li>
            </ul>

          <h2>5. Intellectual Property</h2>
          <p>
            The application, including without limitation all copyrights, patents, trademarks, trade secrets, 
            and other intellectual property rights are, and shall remain, the sole and exclusive property of Focus Train.
          </p>

          <h2>6. User Data</h2>
          <p>
            Focus Train is designed to be privacy-first. We do not collect personal data. Any data generated by 
            your use of the application (such as focus session history or settings) is stored locally on your device.
          </p>

          <h2>7. Updates to Application</h2>
          <p>
            We may from time to time provide enhancements or improvements to the features and functionality of the 
            application, which may include patches, bug fixes, updates, upgrades, and other modifications.
          </p>

          <h2>8. Term and Termination</h2>
          <p>
            This Agreement shall remain in effect until terminated by you or us. We may, in our sole discretion, 
            at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
          </p>
          
          <h2>9. Disclaimer of Warranty</h2>
          <p>
            The Application is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. 
            To the maximum extent permitted under applicable law, we expressly disclaim all warranties, whether express, implied, statutory, or otherwise.
          </p>

          <h2>10. Subscription Terms and Licensed Application End User License Agreement</h2>
          <p>
            Focus Train offers auto-renewable subscriptions for access to premium features.
            The App is licensed, not sold, to you. Your license to the App is subject to your prior
            acceptance of this End User License Agreement ("Agreement"). Your license to the App
            under this Agreement is granted by Focus Train ("Licensor"). Licensor reserves all rights
            in and to the App not expressly granted to you under this Agreement.
          </p>

          <h3>a. Auto-Renewable Subscriptions</h3>
          <ul>
            <li><strong>Payment charging:</strong> Payment will be charged to your Apple ID account at confirmation of purchase.</li>
            <li><strong>Auto-renewal rules:</strong> The subscription automatically renews unless it is canceled at least 24 hours before the end of the current period.</li>
            <li><strong>Renewal billing:</strong> Your account will be charged for renewal within 24 hours prior to the end of the current period.</li>
            <li><strong>Management & Cancellation:</strong> You can manage and cancel your subscriptions by going to your App Store account settings after purchase.</li>
          </ul>

          <h3>b. Scope of License:</h3>
          <p>
            Licensor grants to you a nontransferable license to use the Licensed Application on any Apple-branded
            products that you own or control and as permitted by the Usage Rules. The terms of this Agreement will
            govern any content, materials, or services accessible from or purchased within the Licensed Application
            as well as upgrades provided by Licensor that replace or supplement the original Licensed Application.
            Except as provided in the Usage Rules, you may not distribute or make the Licensed Application available
            over a network where it could be used by multiple devices at the same time. You may not transfer, redistribute
            or sublicense the Licensed Application. You may not copy (except as permitted by this license and the Usage Rules),
            reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the
            Licensed Application, any updates, or any part thereof.
          </p>

          <h3>c. Consent to Use of Data:</h3>
          <p>
            You agree that Licensor may collect and use technical data and related information, including but not limited
            to technical information about your device, system and application software, and peripherals, that is gathered
            periodically to facilitate the provision of software updates, product support, and other services to you (if any)
            related to the Licensed Application. Licensor may use this information, as long as it is in a form that does not
            personally identify you, to improve its products or to provide services or technologies to you.
            <em>Note: As stated in Section 6, Focus Train prioritizes privacy and stores core user data locally.</em>
          </p>

          <h3>d. Termination:</h3>
          <p>
            This Agreement is effective until terminated by you or Licensor. Your rights under this Agreement will
            terminate automatically if you fail to comply with any of its terms.
          </p>

          <h3>e. External Services:</h3>
          <p>
            The Licensed Application may enable access to Licensor's and/or third-party services and websites
            (collectively and individually, "External Services"). You agree to use the External Services at your sole risk.
            Licensor is not responsible for examining or evaluating the content or accuracy of any third-party External Services,
            and shall not be liable for any such third-party External Services. Data displayed by any Licensed Application or
            External Service is for general informational purposes only and is not guaranteed by Licensor or its agents.
          </p>

          <h3>f. Governing Law:</h3>
          <p>
            Except to the extent expressly provided in the following paragraph, this Agreement and the relationship between you
            and Focus Train shall be governed by the laws of the applicable jurisdiction where Focus Train operates, excluding its
            conflicts of law provisions. If you are a citizen of any European Union country or Switzerland, Norway or Iceland,
            the governing law and forum shall be the laws and courts of your usual place of residence. Specifically excluded from
            application to this Agreement is that law known as the United Nations Convention on the International Sale of Goods.
          </p>

          <h2>11. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, in no event shall Focus Train be liable for any 
            indirect, punitive, incidental, special, consequential, or exemplary damages, including without 
            limitation damages for loss of profits, goodwill, use, data, or other intangible losses.
          </p>
        </div>
      </section>

      <section class="hero" style="text-align: left; max-width: 800px; padding-bottom: 40px; padding-top: 0;">
        <h1 class="hero-title" style="font-size: 2.5rem; margin-bottom: 40px;">Privacy Policy</h1>
        
        <div class="terms-content">
          <h2>1. Introduction</h2>
          <p>
            This Privacy Policy describes how Focus Train ("we," "our," or "us") handles information 
            when you use our mobile application. We are committed to protecting your privacy.
          </p>

          <h2>2. Information We Collect</h2>
          <p>
            Focus Train is designed with privacy at its core. We do not collect, store, or transmit 
            any personal information. All data related to your focus sessions, preferences, and settings 
            remains on your device.
          </p>

          <h2>3. Data Storage</h2>
          <p>
            All application data is stored locally on your device. We do not use cloud storage, 
            external servers, or any third-party services to store your data. If you delete the 
            application, all associated data will be removed from your device.
          </p>

          <h2>4. Third-Party Services</h2>
          <p>
            Focus Train does not integrate with any third-party analytics, advertising, or tracking 
            services. We do not share any information with third parties.
          </p>

          <h2>5. Children's Privacy</h2>
          <p>
            Our application does not address anyone under the age of 13. We do not knowingly collect 
            personally identifiable information from children under 13.
          </p>

          <h2>6. Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by 
            posting the new Privacy Policy on this page with an updated revision date.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact us at 
            <a href="mailto:trainfocus@proton.me" style="color: var(--color-primary); text-decoration: underline;">trainfocus@proton.me</a>.
          </p>
          
          <p style="margin-top: 40px; color: var(--color-text-light); font-size: 0.9rem;">
            Last updated: March 9, 2026
          </p>
        </div>
      </section>
    </main>

    <footer class="footer">
      <div class="container footer-content">
        <p>&copy; {{ new Date().getFullYear() }} Focus Train. All rights reserved.</p>
      </div>
    </footer>
  </div>
</template>

<style src="./focustrain.css"></style>

<style scoped>
.terms-content {
  color: var(--color-text);
  line-height: 1.8;
}

.terms-content h2 {
  font-size: 1.5rem;
  margin-top: 32px;
  margin-bottom: 16px;
  font-weight: 600;
  color: var(--color-text);
}

.terms-content h3 {
  font-size: 1.15rem;
  margin-top: 24px;
  margin-bottom: 12px;
  font-weight: 600;
  color: var(--color-text);
}

.terms-content p {
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content ul {
  padding-left: 24px;
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content li {
  margin-bottom: 8px;
}

.nav-icon {
  width: 32px;
  height: 32px;
  border-radius: 6px;
}
</style>
