<template>
  <div class="app-wrapper">
    <nav class="navbar">
      <div class="container nav-content">
        <div class="brand">
          <span class="nav-title">文 - Karacter</span>
        </div>
        <RouterLink to="/karacter" class="back-link">← back to app</RouterLink>
      </div>
    </nav>

    <main class="container">
      <section class="hero" style="text-align: left; max-width: 800px; padding-bottom: 40px;">
        <h1 class="hero-title" style="font-size: 2.5rem; margin-bottom: 40px;">Terms and Conditions</h1>
        
        <div class="terms-content">
          <h2>1. Introduction</h2>
          <p>
            Welcome to Karacter ("we," "our," or "us"). By downloading or using our mobile application, 
            you agree to be bound by these Terms and Conditions. If you do not agree to these terms, 
            please do not use the application.
          </p>

          <h2>2. License</h2>
          <p>
            We grant you a revocable, non-exclusive, non-transferable, limited license to download, 
            install, and use the application strictly in accordance with these Terms.
          </p>

          <h2>3. Usage Restrictions</h2>
          <p>
            You agree not to, and you will not permit others to:
          </p>
            <ul>
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the application.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the application.</li>
              <li>Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of us or our affiliates, partners, suppliers, or the licensors of the application.</li>
            </ul>

          <h2>4. Intellectual Property</h2>
          <p>
            The application, including without limitation all copyrights, patents, trademarks, trade secrets, 
            and other intellectual property rights are, and shall remain, the sole and exclusive property of Karacter.
          </p>

          <h2>5. User Data</h2>
          <p>
            Karacter is designed to be privacy-first. We do not collect personal data. Any data generated by 
            your use of the application (such as potential vocabulary lists or history) is stored locally on your device.
          </p>

          <h2>6. Updates to Application</h2>
          <p>
            We may from time to time provide enhancements or improvements to the features/functionality of the 
            application, which may include patches, bug fixes, updates, upgrades, and other modifications.
          </p>

          <h2>7. Term and Termination</h2>
          <p>
            This Agreement shall remain in effect until terminated by you or us. We may, in our sole discretion, 
            at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
          </p>
          
          <h2>8. Disclaimer of Warranty</h2>
          <p>
             The Application is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, we expressly disclaim all warranties, whether express, implied, statutory, or otherwise.
          </p>
          
          <p style="margin-top: 40px; color: var(--color-text-light); font-size: 0.9rem;">
            Last updated: January 23, 2026
          </p>
        </div>
      </section>
    </main>

    <footer class="footer">
      <div class="container footer-content">
        <p>&copy; {{ new Date().getFullYear() }} Karacter. All rights reserved.</p>
      </div>
    </footer>
  </div>
</template>

<style scoped>
.terms-content {
  color: var(--color-text);
  line-height: 1.8;
}

.terms-content h2 {
  font-size: 1.5rem;
  margin-top: 32px;
  margin-bottom: 16px;
  font-weight: 600;
  color: var(--color-text);
}

.terms-content p {
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content ul {
  padding-left: 24px;
  margin-bottom: 16px;
  color: var(--color-text-light);
}

.terms-content li {
  margin-bottom: 8px;
}
</style>
